baseURL: 'https://abc202313746.github.io/'
title: '인숙영의 포트폴리오'
defaultContentLanguage: ko
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: false
disableLanguages: []
enableRobotsTXT: true
buildFuture: true

ignoreLogs: ['warning-goldmark-raw-html']

disableKinds: ["taxonomy", "term"]

outputs:
  home: ["HTML", "RSS", "JSON", "headers", "redirects"]
  section: ["HTML", "RSS", "JSON"]
  page: ["HTML"]

params:
  logo: 'chat-logo.svg'
  images: ['uploads/aldi-sigun-K-sdQ12jZeY-unsplash (1).jpg']
  
  show_language_switcher: true
  
  assets:
    css_bundle: false
    js_bundle: false



googleAnalytics: ""

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml

markup:
  goldmark:
    renderer:
      unsafe: true

minify:
  disableCSS: true
  disableJS: true
  disableHTML: false
  disableJSON: false
  disableSVG: false
  disableXML: false

build:
  writeStats: false
  noJSConfigInAssets: true

module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5


security:
  funcs:
    getenv:
      - ^HUGO_
      - ^CI$
      - ^WC_
  http:
    urls:
      - '.*'