baseURL: 'https://abc202313746.github.io/'
title: '인숙영의 포트폴리오'
defaultContentLanguage: ko
hasCJKLanguage: true
defaultContentLanguageInSubdir: false

languages:
  ko:
    languageCode: ko-KR
    weight: 1
  en:
    languageCode: en-US
    weight: 2

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml


module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5

############################
## SECURITY
############################

security:
  funcs:
    getenv:
      - ^HUGO_
      - ^CI$
      - ^WC_