baseURL: 'https://abc202313746.github.io/'
title: '인숙영의 포트폴리오'
defaultContentLanguage: ko
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: false
disableLanguages: []
buildFuture: true

disableKinds: ["taxonomy", "term"]

outputs:
  home: ["HTML", "RSS", "JSON", "headers", "redirects"]
  section: ["HTML", "RSS", "JSON"]
  page: ["HTML"]

params:
  logo: 'chat-logo.svg'
  images: ['uploads/og-image.png']
  
  # Language switcher
  show_language_switcher: true
  
  assets:
    css_bundle: false
    js_bundle: false


sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml

minify:
  disableCSS: true
  disableJS: true
  disableHTML: false
  disableJSON: false
  disableSVG: false
  disableXML: false

build:
  writeStats: false
  noJSConfigInAssets: true

module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5


security:
  funcs:
    getenv:
      - ^HUGO_
      - ^CI$
      - ^WC_