baseURL: 'https://abc202313746.github.io/'
title: '인숙영의 포트폴리오'
defaultContentLanguage: ko
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: false
disableLanguages: []

# Disable taxonomy pages (tags, categories)
disableKinds: ["taxonomy", "term"]

# Enable search index generation for all page types
outputs:
  home: ["HTML", "RSS", "JSON", "headers", "redirects"]
  section: ["HTML", "RSS", "JSON"]
  page: ["HTML"]

params:
  logo: 'chat-logo.svg'
  # Default Open Graph image for homepage
  images: ['uploads/og-image.png']

# Languages are configured in languages.yaml

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml


module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5

############################
## SECURITY
############################

security:
  funcs:
    getenv:
      - ^HUGO_
      - ^CI$
      - ^WC_