baseURL: 'https://abc202313746.github.io/'
title: '인숙영의 포트폴리오'
defaultContentLanguage: en
hasCJKLanguage: true
defaultContentLanguageInSubdir: false

languages:
  en:
    languageCode: en-US
    weight: 1
  ko:
    languageCode: ko-KR
    weight: 2


module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5