
ko:
  languageCode: ko-KR
  languageName: 한국어
  contentDir: content
  weight: 1
  title: "인숙영의 포트폴리오"
  params:
    description: "전북대학교 컴퓨터인공지능학부 인숙영의 포트폴리오"
  menu:
    main:
      - name: 홈
        url: '/'
        weight: 10
      - name: 프로젝트
        identifier: projects
        url: '/project/'
        weight: 20
      - name: 데이터베이스
        parent: projects
        url: '/project/database/'
        weight: 21
      - name: 운영체제
        parent: projects
        url: '/project/os/'
        weight: 22
      - name: 스택
        parent: projects
        url: '/project/stack/'
        weight: 23
      - name: 경력
        url: '/experience/'
        weight: 30
      - name: 연락처
        url: '/contact/'
        weight: 40
      - name: 이력서
        url: '/uploads/resume.pdf'
        weight: 50


en:
  languageCode: en-US
  languageName: English
  contentDir: content
  weight: 2
  title: "SookYoung In Portfolio"
  params:
    description: "SookYoung In - Computer Science & AI Student Portfolio"
  menu:
    main:
      - name: Home
        url: '/en/'
        weight: 10
      - name: Projects
        identifier: projects
        url: '/en/project/'
        weight: 20
      - name: Database
        parent: projects
        url: '/en/project/database/'
        weight: 21
      - name: OS
        parent: projects
        url: '/en/project/os/'
        weight: 22
      - name: Stack
        parent: projects
        url: '/en/project/stack/'
        weight: 23
      - name: Experience
        url: '/en/experience/'
        weight: 30
      - name: Contact
        url: '/en/contact/'
        weight: 40
      - name: Resumé
        url: 'https://abc202313746.github.io/uploads/resume.pdf'
        weight: 50
        params:
          target: "_blank"