# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language (Korean)
ko:
  languageCode: ko-KR
  contentDir: content
  weight: 1
  title: "인숙영의 포트폴리오"
  params:
    description: "전북대학교 컴퓨터공학부 인숙영의 포트폴리오"

# English language
en:
  languageCode: en-US
  contentDir: content
  weight: 2
  title: "SookYoung In Portfolio"
  params:
    description: "SookYoung In - Computer Science Student Portfolio"