
main:
  - name: Home
    url: '/en/'
    weight: 10

  - name: Projects
    identifier: projects
    url: '/en/project/'
    weight: 20

  - name: Database
    parent: projects
    url: '/en/project/database/'
    weight: 21

  - name: OS
    parent: projects
    url: '/en/project/os/'
    weight: 22

  - name: Stack
    parent: projects
    url: '/en/project/stack/'
    weight: 23

  - name: Languages
    identifier: languages
    url: '/en/languages/'
    weight: 25

  - name: C Language
    parent: languages
    url: '/en/languages/c-language/'
    weight: 26

  - name: Java
    parent: languages
    url: '/en/languages/java/'
    weight: 27

  - name: Python
    parent: languages
    url: '/en/languages/python/'
    weight: 28

  - name: Experience
    url: '/en/experience/'
    weight: 30

  - name: Contact
    url: '/en/contact/'
    weight: 40
