main:
  - name: 홈
    url: '/'
    weight: 10

  - name: 프로젝트
    identifier: projects
    url: '/project/'
    weight: 20

  - name: 데이터베이스
    parent: projects
    url: '/project/database/'
    weight: 21

  - name: 운영체제
    parent: projects
    url: '/project/os/'
    weight: 22

  - name: 스택
    parent: projects
    url: '/project/stack/'
    weight: 23

  - name: 언어
    identifier: languages
    url: '/languages/'
    weight: 25

  - name: C언어
    parent: languages
    url: '/languages/c-language/'
    weight: 26

  - name: Java
    parent: languages
    url: '/languages/java/'
    weight: 27

  - name: Python
    parent: languages
    url: '/languages/python/'
    weight: 28

  - name: 경력
    url: '/ko/experience/'
    weight: 30

  - name: 연락처
    url: '/ko/contact/'
    weight: 40

  - name: 이력서
    url: 'https://abc202313746.github.io/uploads/resume.pdf'
    weight: 50
    params:
      target: "_blank"


