# Navigation Links for English
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links appear in.

main:
  - name: Home
    url: '/en/'
    weight: 10

  - name: Projects
    identifier: projects
    url: '/en/project/'
    weight: 20

  # Project sub-menu items (parent-child relationship)
  - name: Database
    parent: projects
    url: '/en/project/database/'
    weight: 21

  - name: OS
    parent: projects
    url: '/en/project/os/'
    weight: 22

  - name: Stack
    parent: projects
    url: '/en/project/stack/'
    weight: 23

  - name: Experience
    url: '/en/experience/'
    weight: 30

  - name: Contact
    url: '/en/contact/'
    weight: 40

  - name: Resumé
    url: '/uploads/resume.pdf'
    weight: 50
