# Navigation Links
#   To link a homepage widget, specify the URL as a hash '#' followed by the filename of the
#   desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# menus.ko.yaml

main:
  - name: 홈
    url: '/'
    weight: 10
  - name: 프로젝트
    identifier: projects
    url: '/ko/project/'
    weight: 20
  - name: 데이터베이스
    parent: projects
    url: '/ko/project/database/'
    weight: 21
  - name: 운영체제
    parent: projects
    url: '/ko/project/os/'
    weight: 22
  - name: 스택
    parent: projects
    url: '/ko/project/stack/'
    weight: 23
  - name: 경력
    url: '/ko/experience/'
    weight: 30
  - name: 연락처
    url: '/ko/contact/'
    weight: 40
  - name: 이력서
    url: '/uploads/resume.pdf'
    weight: 50
   